services:
  postgre:
    image: postgres:13.13
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: pg1234
      POSTGRES_USER: kubenews
      POSTGRES_DB: kubenews
  kubenews:
    depends_on:
      - postgre
    image: willosouza/kube-news:v1
    build:
      context: ./src
      dockerfile: ./src/Dockerfile
    ports:
      - 8080:8080
    environment:
      DB_DATABASE: kubenews
      DB_USERNAME: kubenews
      DB_PASSWORD: pg1234
      DB_HOST: postgre
    restart: always

networks:
  kubenews_net:
    driver: bridge
